version: "3"
services:
  application:
    image: "rinha-application"
    build: 
      context: .
      dockerfile: ./Dockerfile
    network_mode: "host"
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      postgres:
        condition: service_healthy
      
  postgres:
    image: postgres:16
    network_mode: "host"
    environment:
      POSTGRES_PASSWORD: "appdb2023!"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5      

  pgadmin:
    image: dpage/pgadmin4
    network_mode: "host"
    environment:
      PGADMIN_DEFAULT_EMAIL: "daniel@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "daniel2023!"
