version: "3"
services:
  application:
    image: "rinha-application"
    build: 
      context: .
      dockerfile: ./Dockerfile
    network_mode: "host"
    ports:
      - 8000:8000
    command:
      - uvicorn 
      - main:app 
      - "--host"
      - "0.0.0.0"
      - "--reload"
    depends_on:
      - postgres
      
  postgres:
    image: postgres:16
    network_mode: "host"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: "appdb2023!"

  pgadmin:
    image: dpage/pgadmin4
    network_mode: "host"
    environment:
      PGADMIN_DEFAULT_EMAIL: "daniel@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "daniel2023!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
