# import redis

# r = redis.Redis(host='127.0.0.1',port=6379,decode_responses=True)
# r.set('foo','bar')
# a = r.get('foo')
# print(a)


# r.delete('my_buffer')
# r.rpush('my_buffer','1')
# r.rpush('my_buffer','2')
# r.rpush('my_buffer','3')
# r.rpush('my_buffer','4')
# r.rpush('my_buffer','5')
# r.rpush('my_buffer','6')
# r.rpush('my_buffer','7')
# queue_len = r.llen('my_buffer')
# print(queue_len)
# objs = r.lrange(name='my_buffer',start=queue_len-3,end=-1)
# print(objs)
# all_objs = r.lrange(name='my_buffer',start=0,end=-1)
# print(all_objs)
# queue_len = r.llen('my_buffer')
# print(queue_len)
# r.ltrim(name='my_buffer',start=queue_len-3,end=-1)
# all_objs = r.lrange(name='my_buffer', start=0, end=-1)
# print(all_objs)
# r.lpop('my_buffer')
# all_objs = r.lrange(name='my_buffer', start=0, end=-1)
# print(all_objs)

from redis_queue2 import RedisQueueFIFO

r = RedisQueueFIFO(queue_key_name='my_queue',lock_key_name='my_lock')
r.acquire_lock()
r.push_elements('a','b','c','d','e','f','g')
print(r.get_elements())
print(r.get_length())
elements_popped = r.pop_elements(quantity=3)
print(f"popped_elements: {elements_popped}")
print(r.get_elements())
print(r.get_length())
r.push_elements('j','l','m')
print(r.get_elements())
print(r.get_length())
r.delete()
r.remove_lock()